// Generated by Wrangler by running `wrangler types`
// Extended with custom bindings

interface Env {
	ENVIRONMENT: "production";
	STORAGE: R2Bucket;
	DB: D1Database;
	GEMINI_API_KEY: string;
	MNEMO_AUTH_TOKEN?: string;
}
